version: '3'

services:

  db:
    image: postgres:13-alpine
    container_name: crm-pilates-postgres
    environment:
      POSTGRES_USER: crm-pilates
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - "./volumes/db/data:/var/lib/postgresql/data"
    build:
      context: .
      target: development

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  crm-pilates-api:
    image: crm-pilates-api:latest
    container_name: crm-pilates-api
    ports:
      - 8081:8081
    volumes:
      - "./command:/app/command"
      - "./domain:/app/domain"
      - "./event:/app/event"
      - "./infrastructure:/app/infrastructure"
      - "./web:/app/web"
    build:
      context: .
      target: development
    depends_on:
      - db
