name: crm-pilates
services:
- dockerfile_path: Dockerfile
  github:
    branch: main
    repo: bbougon/crm-pilates
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: crm-pilates
  routes:
  - path: /crm-pilates
  source_dir: /
  health_checks:
    - http: /health
