root_dir: "{{ (playbook_dir + '/../..') | realpath }}"
event_store_path: "{{ root_dir }}/local.persistent/event/event_store.db"
cors_allow_origins: "*"
database_url: "postgresql://crm-pilates-test:example@localhost:5433/crm-pilates-test"
secret_key: "683ed7b9228d007f40b60de125fbb35681e94bdd23c45e2e0394fe470e1d55bb"
migration_scripts: "crm_pilates/infrastructure/migration/"
