- name: Configure settings
  hosts: all
  roles:
    - role: settings

- name: Configure test environment variable
  hosts: test
  roles:
    - role: environment

- name: Deploy
  hosts:
    deploy
    docker-local
  roles:
    - role: server