- name: Configure settings
  hosts: all
  roles:
    - role: settings

- name: Configure test environment variable
  hosts: test
  environment:
    USER: crm-pilates
    PASSWORD: example
    HOST: localhost
    PORT: 5432
    DBNAME: crm-pilates

- name: Deploy
  hosts:
    deploy
    docker-local
  roles:
    - role: server